BACK_COLOUR = "WHITE"
LINE_COLOUR = "BLACK"
TEXT_COLOUR = 'BLACK'
TEXT_IMAGE_OFFSET = 10
TEXT_IMAGE_RESIZE_VERT = 0.4
TEXT_IMAGE_RESIZE_HORIZ = 0.3
LINE_WIDTH = 5
IMAGE_FUDGE = 10
SIDE_LENGTH = 300
COMB_IM_FUDGE = 10
GAP_IN_FINAL_IMAGE = 50
FIXED_CHAR_WIDTH = 20
TEXT_OVERLAP_FACTOR = 0.8

WIDTH_TREASURE_CLUE = 380

TH_ASPECT_RATIO = 0.8
TH_CLUES_PER_ROW = 3

TEXT_SIZE = 20

USE_TEMP_W = 150
USE_TEMP_H = 100
