BACK_COLOUR = "WHITE"
LINE_COLOUR = "BLACK"
TEXT_COLOUR = 'BLACK'
TEXT_IMAGE_OFFSET = 10
TEXT_IMAGE_RESIZE_VERT = 0.4
TEXT_IMAGE_RESIZE_HORIZ = 0.3
LINE_WIDTH = 5
IMAGE_FUDGE = 10
SIDE_LENGTH = 300
COMB_IM_FUDGE = 10
GAP_IN_FINAL_IMAGE = 50

FONT_URL = 'https://github.com/googlefonts/roboto/blob/main/src/hinted/Roboto-Light.ttf?raw=true'
TEXT_SIZE = 20
